### ISSUE TITLE
Report utf-8-sig

### ISSUE THREAD

**Issue by jayvdb** [Joungkyun/python-chardet#3]
A file with a UTF-8 BOM is detected as 'utf-8' when it should ideally be 'utf-8-sig'.  This is really important because lots of tools re-open the file using the detected encoding, and 'utf-8-sig' will strip the bom but 'utf-8' will not, and the BOM will cause breakages.

I realise that `utf-8-sig` is a Python-ism, but the libchardet could provide some extra flags in its results which `python-chardet` could check to known when to append the `-sig`.

Other differences when compared with other libraries:

utf16* are detected as 'utf-16le' and 'utf-16be', which is great because many detection libraries just report 'utf-16'.  It is odd that this library is reporting the endianness of utf-16, but is not reporting the `-sig` when the BOM appears in utf-8.

Curly quotes in ascii are detected as 'windows-1250', which decodes correctly. \o/  Libraries which detect this often detect it as 'windows-1252', but that is an internal/arbitrary choice not based on the input text.

UTF-7 problems like reported at https://github.com/PyYoshi/uchardet/issues/4 , and the other BOMs reported there, also occur in this library.

**Comment by Joungkyun** [comment]
It is a good opinion. When I made the detector, I thought it was not important to judge the BOM, so I ignored it.

However, this is not a problem with python-chardet, but with libchardet.
So I will continue with the issue of libchardet.

**Comment by Joungkyun** [comment]
@jayvdb If detecting BOM, return to "UTF-8-SIG" or another expression?

| No BOM | BOM |
| -- | -- |
| UTF-8 | UTF-8-SIG |
| BOCU-1 | BOCU-1-SIG |
| GB18030 | GB18030-SIG |
| SCSU | SCSU-SIG |
| UTF-1 | UTF-1-SIG |
| UTF-7 | UTF-7-SIG |
| UTF-EBCDIC | UTF-EBCDIC-SIG |

right ? can you agree?

**Comment by jayvdb** [comment]
That is a reasonable solution.

**Comment by jayvdb** [comment]
The problem with that is `GB18030` and `UTF-7` are supported codecs in Python, while `GB18030-SIG` and `UTF-7-SIG` are not.

A *very* common usage of chardet is to use the `encoding` as `open(..., encoding=encoding)` , and that will fail if the codec isnt recognised by Python.

One solution for that is to also register codecs for `GB18030-SIG` and `UTF-7-SIG` which remove the BOM like `UTF-8-SIG` does.

**Comment by Joungkyun** [comment]
> One solution for that is to also register codecs for GB18030-SIG and UTF-7-SIG which remove the BOM like UTF-8-SIG does.

One solution for that is to also register codecs for GB18030-SIG and UTF-7-SIG which remove the BOM like UTF-8-SIG does.

I have confirmed that utf-8-sig is only present in pyhton. And python seems to only check for BOM in UTF-8.

So, in python-chatdet, I will only support utf-8-sig. And the others will be returned with is_bom member that is  setted 1 if bom is exists.

How about your opinion?

**Comment by jayvdb** [comment]
That is the most compatible solution.

I can update https://github.com/timrburnham/bom_open to explicitly look for `is_bom` and it can handle the BOM internally.

**Comment by Joungkyun** [comment]
I had another high priority jobs. I will follow up again after a week.

**Comment by Joungkyun** [comment]
This feature supports UTF-8-SIG for UTF8 with BOM in libchardet 1.0.6 or later. In the 1.0.5 and before, it is treated as UTF-8. 

```
=================================================
** Python chardet_c init / detect / close test **
=================================================

Python chardet c binding module version: 2.0.1
URL windows-1256.txt     : encoding: windows-1256   , confidence: 0.79
URL windows-1251.txt     : encoding: windows-1251   , confidence: 0.79
URL windows-1252.txt     : encoding: windows-1252   , confidence: 0.87
URL windows-1253.txt     : encoding: windows-1253   , confidence: 0.82
URL ascii.txt            : encoding: ASCII          , confidence: 1.00
URL iso-8859-15.txt      : encoding: Big5           , confidence: 0.99
URL iso-8859-8.txt       : encoding: windows-1255   , confidence: 0.77
URL euc-jp.txt           : encoding: EUC-JP         , confidence: 1.00
URL iso-2022-jp.txt      : encoding: ISO-2022-JP    , confidence: 0.99
URL shift_jis.txt        : encoding: Shift_JIS      , confidence: 0.99
URL euc-kr.smi           : encoding: EUC-KR         , confidence: 0.99
URL iso-2022-kr.txt      : encoding: ISO-2022-KR    , confidence: 0.99
URL ibm866.txt           : encoding: IBM866         , confidence: 0.81
URL tis-620.txt          : encoding: TIS-620        , confidence: 0.60
URL iso-8859-9.txt       : encoding: ISO-8859-9     , confidence: 0.86
URL viscii.txt           : encoding: VISCII         , confidence: 0.63
URL big5.txt             : encoding: Big5           , confidence: 0.99
URL euc-tw.txt           : encoding: EUC-TW         , confidence: 0.99
URL gb18030.txt          : encoding: GB18030        , confidence: 0.99
URL utf-8.txt            : encoding: UTF-8          , confidence: 0.99
URL utf-8-bom.txt        : encoding: UTF-8-SIG      , confidence: 1.00
```
