### ISSUE TITLE
Compatibility with traditional chardet

### ISSUE THREAD

**Issue by jayvdb** [Joungkyun/python-chardet#4]
This package should try to maintain compatibility with the traditional chardet, or document any differences.

It would be nice to run a modified copy of their test suite, and periodically sync it.

chardet master has introduced `detect_all` which returns an array of results.

**Comment by Joungkyun** [comment]
Because this module uses the API of the libchardet C Library, it is difficult to implement detect_all.

As your opinion, need to document the difference from the traditional chardet.

**Comment by Joungkyun** [comment]
chardet.detect_all is implemented as follows:

```python
def detect_all(aBuf) :
    r = _chardet.detect (aBuf);
    return [r]
```

It is provided only for API compatibility with the tranditional chardet. It actually returns the same result as ```chardet.detect```. (Only data types are different.)
