### ISSUE TITLE
Use pkgconfig

### ISSUE THREAD

**Issue by jayvdb** [Joungkyun/python-chardet#5]
`setup.py` uses `chardet-config` which is nice, except that it is broken on openSUSE and the maintainers recommend using pkgconfig instead.  see https://build.opensuse.org/request/show/720085

libchardet does include a .pc , so it could be used instead.

**Comment by jayvdb** [comment]
https://github.com/peterjc/backports.lzma/pull/11 and https://github.com/python-lz4/python-lz4/pull/76 use package `pkgconfig` to simplify this.

**Comment by Joungkyun** [comment]
I tested it as follows:

```python
    import pkgconfig

    pkg = pkgconfig.parse ('chardet')
    libdir.append (pkg['library_dirs'])
    incdir.append (pkg['include_dirs'])
```

However, in the test, an error occurs as follows:

```
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I[u'/usr/include/chardet'] -I/usr/include/python2.7 -c src/chardet.c -o build/temp.linux-x86_64-2.7/src/chardet.o
src/chardet.c:18:21: fatal error: chardet.h: can not found
 #include <chardet.h>
                     ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```

When using the PKGConfig module, additional parsing is more required, and the code complexity seems to be higher. 

```
-I[u'/usr/include/chardet'] -> -I/usr/include/chardet
```

**Comment by jayvdb** [comment]
That is because each library can have more than one directory for includes and libs. No parsing is needed.
Use
```py
    libdir += pkg['library_dirs'])
    incdir += pkg['include_dirs'])
```

**Comment by Joungkyun** [comment]
> 
> 
> That is because each library can have more than one directory for includes and libs. No parsing is needed.
> Use
> 
> ```python
>     libdir += pkg['library_dirs'])
>     incdir += pkg['include_dirs'])
> ```

sound good. thanks
